In [1]:
%pip install seaborn
#seabornをインストール

Requirement already satisfied: seaborn in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from seaborn) (2.5.3)
Requirement already satisfied: pandas>=1.2 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from seaborn) (3.0.6)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from seaborn) (3.11.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\NDY13\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.2->seaborn) (2026.4)
Requirement already satisfied: six>=1.5 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
#ライブラリをインポート
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Cythonをインストール
%pip install Cython

Requirement already satisfied: Cython in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.3.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
#sklearnをインストール
import sklearn 
sklearn.set_config(display="text")

In [6]:
#線形モデルをインポート
%pip install scikit-learn
from sklearn.linear_model import LinearRegression as LR
%matplotlib inline

Requirement already satisfied: scikit-learn in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.5.3)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

In [8]:
#学習データの読み込み
train = pd.read_csv("train.csv")
#検証用データの読み込み
test = pd.read_csv("test.csv")
#提出用サンプルデータの読み込み
sample = pd.read_csv("sample.csv", header=None)

#データ確認
train.head(5)

,datetime,y,week,soldout,name,kcal,remarks,event,payday,weather,precipitation,temperature
0,2013-11-18,90,月,0,厚切りイカフライ,NaN,NaN,NaN,NaN,快晴,--,19.8
1,2013-11-19,101,火,1,手作りヒレカツ,NaN,NaN,NaN,NaN,快晴,--,17.0
2,2013-11-20,118,水,0,白身魚唐揚げ野菜あん,NaN,NaN,NaN,NaN,快晴,--,15.5
3,2013-11-21,120,木,1,若鶏ピリ辛焼,NaN,NaN,NaN,NaN,快晴,--,15.2
4,2013-11-22,130,金,1,ビッグメンチカツ,NaN,NaN,NaN,NaN,快晴,--,16.1

In [9]:
test.head()

,datetime,week,soldout,name,kcal,remarks,event,payday,weather,precipitation,temperature
0,2014-10-1,水,1,メンチカツ,420.0,NaN,NaN,NaN,雨,0,20.2
1,2014-10-2,木,0,バーベキューチキン,415.0,NaN,NaN,NaN,曇,--,23.9
2,2014-10-3,金,0,豚肉のマスタード焼き,405.0,NaN,NaN,NaN,晴れ,--,28.7
3,2014-10-6,月,1,麻婆春雨,400.0,NaN,NaN,NaN,雨,0.5,21.5
4,2014-10-7,火,0,厚揚げ肉みそ炒め,430.0,NaN,NaN,NaN,晴れ,--,22.1

In [10]:
#データ分離用のフラグを立てる
train["fig"] =1
test["fig"] =0

In [11]:
#trainとtestを結合する
all_data = pd.concat([train,test],axis=0,sort=False)
all_data.head()

,datetime,y,week,soldout,name,kcal,remarks,event,payday,weather,precipitation,temperature,fig
0,2013-11-18,90.0,月,0,厚切りイカフライ,NaN,NaN,NaN,NaN,快晴,--,19.8,1
1,2013-11-19,101.0,火,1,手作りヒレカツ,NaN,NaN,NaN,NaN,快晴,--,17.0,1
2,2013-11-20,118.0,水,0,白身魚唐揚げ野菜あん,NaN,NaN,NaN,NaN,快晴,--,15.5,1
3,2013-11-21,120.0,木,1,若鶏ピリ辛焼,NaN,NaN,NaN,NaN,快晴,--,15.2,1
4,2013-11-22,130.0,金,1,ビッグメンチカツ,NaN,NaN,NaN,NaN,快晴,--,16.1,1

In [12]:
#欠損数、型を確認する
all_data.info()

<class 'pandas.DataFrame'>
Index: 247 entries, 0 to 39
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   datetime       247 non-null    str
 1   y              207 non-null    float64
 2   week           247 non-null    str
 3   soldout        247 non-null    int64
 4   name           247 non-null    str
 5   kcal           202 non-null    float64
 6   remarks        28 non-null     str
 7   event          17 non-null     str
 8   payday         12 non-null     float64
 9   weather        247 non-null    str
 10  precipitation  247 non-null    str
 11  temperature    247 non-null    float64
 12  fig            247 non-null    int64
dtypes: float64(4), int64(2), str(7)
memory usage: 27.0 KB

In [13]:
#NaNの数を確認する
all_data.isnull().sum()

datetime           0
y                 40
week               0
soldout            0
name               0
kcal              45
remarks          219
event            230
payday           235
weather            0
precipitation      0
temperature        0
fig                0
dtype: int64

In [15]:
#kcalの欠損値を平均値で補完する
all_data["kcal"] = all_data["kcal"].fillna(all_data["kcal"].mean())
all_data.isnull().sum()

datetime           0
y                 40
week               0
soldout            0
name               0
kcal               0
remarks          219
event            230
payday           235
weather            0
precipitation      0
temperature        0
fig                0
dtype: int64

In [16]:
#補完の確認
all_data["kcal"].head()

0    407.381188
1    407.381188
2    407.381188
3    407.381188
4    407.381188
Name: kcal, dtype: float64

In [ ]:
#paydayの有無を確認する