In [54]:
%pip install seaborn
#sns インストール

Requirement already satisfied: seaborn in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from seaborn) (2.5.3)
Requirement already satisfied: pandas>=1.2 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from seaborn) (3.0.6)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from seaborn) (3.11.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\NDY13\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.2->seaborn) (2026.4)
Requirement already satisfied: six>=1.5 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [55]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
#ライブラリをインポート

In [56]:
train = pd.read_csv('train.csv') # 学習データの読み込み
test = pd.read_csv('test.csv') # 検証データの読み込み
sample = pd.read_csv('sample.csv', header=None) # 提出用サンプルデータの読み込み

# データ確認
train.head()

,datetime,y,week,soldout,name,kcal,remarks,event,payday,weather,precipitation,temperature
0,2013-11-18,90,月,0,厚切りイカフライ,NaN,NaN,NaN,NaN,快晴,--,19.8
1,2013-11-19,101,火,1,手作りヒレカツ,NaN,NaN,NaN,NaN,快晴,--,17.0
2,2013-11-20,118,水,0,白身魚唐揚げ野菜あん,NaN,NaN,NaN,NaN,快晴,--,15.5
3,2013-11-21,120,木,1,若鶏ピリ辛焼,NaN,NaN,NaN,NaN,快晴,--,15.2
4,2013-11-22,130,金,1,ビッグメンチカツ,NaN,NaN,NaN,NaN,快晴,--,16.1

In [57]:
train.isnull().sum()
#Nullの数を調べる

datetime           0
y                  0
week               0
soldout            0
name               0
kcal              41
remarks          186
event            193
payday           197
weather            0
precipitation      0
temperature        0
dtype: int64

In [58]:
#データの概要を知る
train.describe()

                y     soldout        kcal  payday  temperature
count  207.000000  207.000000  166.000000    10.0   207.000000
mean    86.623188    0.449275  404.409639     1.0    19.252174
std     32.882448    0.498626   29.884641     0.0     8.611365
min     29.000000    0.000000  315.000000     1.0     1.200000
25%     57.000000    0.000000  386.000000     1.0    11.550000
50%     78.000000    0.000000  408.500000     1.0    19.800000
75%    113.000000    1.000000  426.000000     1.0    26.100000
max    171.000000    1.000000  462.000000     1.0    34.600000

In [59]:
# 学習用データ
# 説明変数に "temperature (温度)" を利用
X_train = train['temperature']
# 目的変数に "y (売り上げ個数)" を利用
y_train = train['y']

# 検証用（予測用）データ
X_test  = test['temperature']

In [60]:
X_train.head()

X_train.shape
# > (207,)

(207,)

In [61]:
X_train = X_train.values.reshape(-1,1)
X_test = X_test.values.reshape(-1,1)
#トレーニングデータとテストデータを一列データにする

In [62]:
print(X_train)
#X_trainを表示

[[19.8]
 [17. ]
 [15.5]
 [15.2]
 [16.1]
 [14.6]
 [17.9]
 [14.7]
 [17.7]
 [12.1]
 [13.8]
 [13.9]
 [13.5]
 [13.8]
 [14.9]
 [ 9.1]
 [ 7.1]
 [11. ]
 [12.3]
 [13.9]
 [11.3]
 [10.8]
 [ 7.8]
 [ 6.8]
 [ 8.4]
 [11.5]
 [ 8. ]
 [ 7.3]
 [ 7.3]
 [ 9.8]
 [10.9]
 [ 5.1]
 [ 5.8]
 [ 2.9]
 [ 7. ]
 [ 7.8]
 [ 6.5]
 [10.4]
 [ 7.4]
 [ 8.5]
 [10.1]
 [ 5.1]
 [12.6]
 [10.3]
 [15.3]
 [14.1]
 [15.9]
 [ 3.8]
 [ 3. ]
 [ 4.2]
 [ 5.5]
 [ 7.8]
 [ 6.3]
 [ 6.4]
 [ 1.2]
 [11.6]
 [ 6.8]
 [ 7.3]
 [ 5.4]
 [ 8.5]
 [ 6.6]
 [10.5]
 [11.5]
 [ 8.5]
 [17.7]
 [ 7.8]
 [ 8.3]
 [ 6.1]
 [ 6.7]
 [ 7. ]
 [ 7.6]
 [ 8.7]
 [14.8]
 [15.2]
 [11.5]
 [14. ]
 [18.9]
 [12.6]
 [ 7.5]
 [17.4]
 [18.9]
 [18.7]
 [12.4]
 [18.5]
 [17.5]
 [16.1]
 [18.2]
 [14.3]
 [17.8]
 [13.8]
 [20.1]
 [19. ]
 [21.3]
 [16.5]
 [16.4]
 [19.7]
 [21.5]
 [20.1]
 [11.4]
 [16.4]
 [18.8]
 [19.4]
 [19.9]
 [20.8]
 [22.7]
 [17.5]
 [24. ]
 [23.3]
 [18.9]
 [21. ]
 [23.4]
 [22.7]
 [18.6]
 [26. ]
 [19.3]
 [23.8]
 [22.8]
 [23.9]
 [17.4]
 [19. ]
 [19.8]
 [23.9]
 [23.7]
 [25.7]
 [26. ]
 [26.9]
 [30.6]
 [27. ]
 [27.5]
 [21.5]
 [19.9]
 [25. ]
 [25.5]
 [22.3]
 [21.3]
 [29.5]
 [28.1]
 [27.6]
 [21.9]
 [27.5]
 [26.5]
 [26.9]
 [23.7]
 [25.2]
 [25.2]
 [25.4]
 [25.5]
 [28.3]
 [28.8]
 [27. ]
 [22.1]
 [24. ]
 [29.7]
 [24.6]
 [28.8]
 [33.9]
 [30.9]
 [30.3]
 [30.9]
 [30.1]
 [25.6]
 [30.2]
 [32. ]
 [32.5]
 [33.6]
 [28.9]
 [30.4]
 [30.6]
 [32.5]
 [32.7]
 [32.7]
 [34.3]
 [34.6]
 [32.1]
 [31.1]
 [32.4]
 [29.4]
 [32.2]
 [33.3]
 [33.3]
 [33. ]
 [33.1]
 [26. ]
 [26.2]
 [21. ]
 [21.6]
 [25.1]
 [23.4]
 [29.1]
 [26.7]
 [26.5]
 [30.2]
 [23.1]
 [26.8]
 [25. ]
 [21.9]
 [27.3]
 [28.8]
 [25. ]
 [24.1]
 [23.6]
 [25.2]
 [24.8]
 [25.4]
 [27.1]
 [26.6]
 [28.1]]

In [63]:
#X_testを表示
print(X_test)

[[20.2]
 [23.9]
 [28.7]
 [21.5]
 [22.1]
 [23.3]
 [22.5]
 [26.1]
 [26.8]
 [15.6]
 [18.6]
 [23. ]
 [23.9]
 [20.2]
 [15.5]
 [14.7]
 [18.7]
 [22.7]
 [19.1]
 [19.6]
 [19.6]
 [18.8]
 [18.9]
 [16. ]
 [19.2]
 [20.1]
 [21.2]
 [14.7]
 [14.4]
 [19.5]
 [15.8]
 [14.3]
 [16.1]
 [14.9]
 [10.5]
 [14.9]
 [11.4]
 [ 9.2]
 [15.1]
 [15.3]]

In [64]:
X_train.shape
#行数と列数を確認

(207, 1)

In [1]:
%pip install Cython
%pip install scikit-learn
from sklearn.linear_model import LinearRegression as LR 
%matplotlib inline 
# 線形回帰のモデルインポート

Requirement already satisfied: Cython in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.3.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: scikit-learn in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.5.3)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\Users\NDY13\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Note: you may need to restart the kernel to use updated packages.